tjf:
  api:
    filter:
      fields:
        enabled: true

sgdp:
  service:
    url: http://sgdp.local:8080
  product:
    id: SGDP Sample APP
 
spring:
    
  application:
    name: sgdp-test-sample
  
  h2:
    console:
      enabled: true
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cash-account;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    username: sa
    password:
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:      
      hibernate:
        format_sql: true

  cloud:
    stream:
      defaultBinder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost

      rabbit:
        bindings:
          sgdp-input:
            consumer:
              exchangeType: headers
          sgdp-audit:
            producer:
              exchangeType: headers
          sgdp-output:
            producer:
              exchangeType: headers 

      bindings:
        sgdp-audit:
          destination: sgdp-audit

        sgdp-input:
          destination: sgdp-commands
          group: sw-sgdp-app

        sgdp-output:
          destination: sgdp-responses
          
        tjf-messaging-error-input:
          destination: error-messaging
          group: errors
        tjf-messaging-error-output:
          destination: error-messaging
          group: errors
          producer:
            requiredGroups: errors         
          
server:
  port: 8180
